version: "3"

services:
  production-server:
    image: atomicsearch/massiveprediction:latest
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-80}
      - REDIS_PORT=6379
      - BASIC_SSL=${BASIC_SSL:-false}
      - IS_CACHE_ENABLED=false
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - production-server
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
