services:
  production-server:
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-7860}
      - BASIC_SSL=${BASIC_SSL:-false}
    ports:
      - "${PORT:-7860}:${PORT:-7860}"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
