version: "3"

services:
  production-server:
    image: atomicsearch/massiveprediction:latest
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-443}
      - REDIS_PORT=6379
      - BASIC_SSL=${BASIC_SSL:-true}
      - IS_CACHE_ENABLED=false
    ports:
      - "${PORT:-80}:80"
      - "${PORT:-443}:443"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
