version: "3"

services:
  production-server:
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-7860}
      - BASIC_SSL=${BASIC_SSL:-false}
      - IS_CACHE_ENABLED=false
    ports:
      - "${PORT:-7860}:${PORT:-7860}"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
