version: "3"

services:
  production-server:
    image: atomicsearch/massiveprediction:latest
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - BASIC_SSL=${BASIC_SSL:-false}
      - IS_CACHE_ENABLED=false
    ports:
      - "80:80"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
