version: "3"
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379" # use non standard port so we don't clash with any existing

  development-server:
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-7860}
      - REDIS_PORT=6379
      - BASIC_SSL=${BASIC_SSL:-false}
      - HMR_PORT=${HMR_PORT:-7861}
      - IS_CACHE_ENABLED=${IS_CACHE_ENABLED:-true}
    ports:
      - "${PORT:-7860}:7860"
      - "${HMR_PORT:-7861}:7861"
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/home/user/app/
    command:
      [
        "/usr/local/searxng/dockerfiles/docker-entrypoint.sh -f & npm install && npm run dev",
      ]
    depends_on:
      - redis
