export const supportedSearchEngines = [
  "9gag",
  "annas archive",
  "apk mirror",
  "apple app store",
  "ahmia",
  "anaconda",
  "arch linux wiki",
  "artic",
  "arxiv",
  "ask",
  "bandcamp",
  "bilibili",
  "bing",
  "bing images",
  "bing news",
  "bing videos",
  "bitbucket",
  "bpb",
  "btdigg",
  "openverse",
  "media.ccc.de",
  "chefkoch",
  "cppreference",
  "crossref",
  "crowdview",
  "yep",
  "yep images",
  "yep news",
  "curlie",
  "currency",
  "bahnhof",
  "deezer",
  "destatis",
  "deviantart",
  "ddg definitions",
  "docker hub",
  "erowid",
  "wikidata",
  "duckduckgo",
  "duckduckgo images",
  "duckduckgo videos",
  "duckduckgo news",
  "duckduckgo weather",
  "apple maps",
  "emojipedia",
  "tineye",
  "etymonline",
  "1x",
  "fdroid",
  "flickr",
  "free software directory",
  "frinkiac",
  "fyyd",
  "genius",
  "gentoo",
  "gitlab",
  "github",
  "codeberg",
  "goodreads",
  "google",
  "google images",
  "google news",
  "google videos",
  "google scholar",
  "google play apps",
  "google play movies",
  "material icons",
  "gpodder",
  "habrahabr",
  "hackernews",
  "hex",
  "hoogle",
  "imdb",
  "imgur",
  "ina",
  "invidious",
  "jisho",
  "kickass",
  "lemmy communities",
  "lemmy users",
  "lemmy posts",
  "lemmy comments",
  "library genesis",
  "z-library",
  "library of congress",
  "libretranslate",
  "lingva",
  "lobste.rs",
  "mastodon users",
  "mastodon hashtags",
  "mdn",
  "metacpan",
  "mixcloud",
  "mozhi",
  "mwmbl",
  "npm",
  "nyaa",
  "mankier",
  "odysee",
  "openairedatasets",
  "openairepublications",
  "openmeteo",
  "openstreetmap",
  "openrepos",
  "packagist",
  "pdbe",
  "photon",
  "pinterest",
  "piped",
  "piped.music",
  "piratebay",
  "pixiv",
  "podcastindex",
  "presearch",
  "presearch images",
  "presearch videos",
  "presearch news",
  "pub.dev",
  "pubmed",
  "pypi",
  "qwant",
  "qwant news",
  "qwant images",
  "qwant videos",
  "radio browser",
  "reddit",
  "rottentomatoes",
  "semantic scholar",
  "sepiasearch",
  "soundcloud",
  "stackoverflow",
  "askubuntu",
  "internetarchivescholar",
  "superuser",
  "searchcode code",
  "startpage",
  "tokyotoshokan",
  "solidtorrents",
  "tagesschau",
  "tmdb",
  "torch",
  "unsplash",
  "yandex music",
  "yahoo",
  "yahoo news",
  "youtube",
  "dailymotion",
  "vimeo",
  "wiby",
  "alexandria",
  "wikibooks",
  "wikinews",
  "wikiquote",
  "wikisource",
  "wikispecies",
  "wiktionary",
  "wikiversity",
  "wikivoyage",
  "wikicommons.images",
  "wikicommons.videos",
  "wikicommons.audio",
  "wikicommons.files",
  "wolframalpha",
  "dictzone",
  "mymemory translated",
  "1337x",
  "duden",
  "seznam",
  "mojeek",
  "moviepilot",
  "naver",
  "rubygems",
  "peertube",
  "mediathekviewweb",
  "yacy",
  "yacy images",
  "rumble",
  "livespace",
  "wordnik",
  "woxikon.de synonyme",
  "seekr news",
  "seekr images",
  "seekr videos",
  "sjp.pwn",
  "stract",
  "svgrepo",
  "tootfinder",
  "voidlinux",
  "wallhaven",
  "wikimini",
  "wttr.in",
  "yummly",
  "brave",
  "brave.images",
  "brave.videos",
  "brave.news",
  "lib.rs",
  "sourcehut",
  "goo",
  "bt4g",
  "pkg.go.dev",
];
