name: Check Docker Container

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    name: Check Docker Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker-compose -f docker-compose.production.yml up -d
      - name: Check if main page is available
        run: |
          timeout 60 bash -c 'until curl -s -o /dev/null -w "%{http_code}" https://localhost | grep 200; do sleep 1; done'
          if [ $? -eq 124 ]; then
            echo "Timed out waiting for the main page to be available"
            exit 1
          fi
      - run: docker-compose -f docker-compose.production.yml down
