name: Service build

on:   
  push:
    branches:
      - main
env:
  SERVICE_NAME: ***
  DOCKER_REPO: ***
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files    
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_REPO }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files    
        uses: actions/checkout@v2
      - name: Updating docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            docker service update --image "${{ env.DOCKER_REPO }}:latest" ${{ env.SERVICE_NAME }} 
